//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juegoBasta
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bastaEntities : DbContext
    {
        public bastaEntities()
            : base("name=bastaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<conversation> conversations { get; set; }
        public virtual DbSet<gamePlayed> gamePlayeds { get; set; }
        public virtual DbSet<gameUser> gameUsers { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<round> rounds { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<typeChat> typeChats { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userConversation> userConversations { get; set; }
    }
}
