//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cliente.ServiceBasta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBasta.IServiceBasta", CallbackContract=typeof(cliente.ServiceBasta.IServiceBastaCallback))]
    public interface IServiceBasta {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceBasta/PruebaConeccion")]
        void PruebaConeccion(int valor);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceBasta/PruebaConeccion")]
        System.Threading.Tasks.Task PruebaConeccionAsync(int valor);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceBasta/AgregarUsuario")]
        void AgregarUsuario(string name, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceBasta/AgregarUsuario")]
        System.Threading.Tasks.Task AgregarUsuarioAsync(string name, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBasta/IniciarSesion", ReplyAction="http://tempuri.org/IServiceBasta/IniciarSesionResponse")]
        bool IniciarSesion(string nombre, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBasta/IniciarSesion", ReplyAction="http://tempuri.org/IServiceBasta/IniciarSesionResponse")]
        System.Threading.Tasks.Task<bool> IniciarSesionAsync(string nombre, string contrasena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBastaCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceBasta/ContestarPrueba")]
        void ContestarPrueba(int valor);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceBasta/NotificarUsuarioAgregado")]
        void NotificarUsuarioAgregado(int resultado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBastaChannel : cliente.ServiceBasta.IServiceBasta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBastaClient : System.ServiceModel.DuplexClientBase<cliente.ServiceBasta.IServiceBasta>, cliente.ServiceBasta.IServiceBasta {
        
        public ServiceBastaClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceBastaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceBastaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBastaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBastaClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void PruebaConeccion(int valor) {
            base.Channel.PruebaConeccion(valor);
        }
        
        public System.Threading.Tasks.Task PruebaConeccionAsync(int valor) {
            return base.Channel.PruebaConeccionAsync(valor);
        }
        
        public void AgregarUsuario(string name, string password, string email) {
            base.Channel.AgregarUsuario(name, password, email);
        }
        
        public System.Threading.Tasks.Task AgregarUsuarioAsync(string name, string password, string email) {
            return base.Channel.AgregarUsuarioAsync(name, password, email);
        }
        
        public bool IniciarSesion(string nombre, string contrasena) {
            return base.Channel.IniciarSesion(nombre, contrasena);
        }
        
        public System.Threading.Tasks.Task<bool> IniciarSesionAsync(string nombre, string contrasena) {
            return base.Channel.IniciarSesionAsync(nombre, contrasena);
        }
    }
}
